### ISSUE TITLE
[mac] build broken

### ISSUE THREAD

**Issue by bgallois** [bgallois/FastTrack#51]
MacOS build in falling with 
`ERROR: Could not parse otool output line: "\t/usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0, reexport)"` error. Build was working 10 days ago.

Related information:
- GCC 1.3.0 released 4 days ago: https://github.com/Homebrew/homebrew-core/commits/fb995692d82503ae8de64333a2be29118119fcaf/Formula/gcc.rb

**Comment by bgallois** [comment]
https://github.com/OpenHantek/OpenHantek6022/issues/296

**Comment by bgallois** [comment]
Using macdeployqt from Qt6.3.0 fix the error on macdeployqt but triggered `ERROR | quitting early: couldn't fix dependency /usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib of FastTrack-cli.app/Contents/Frameworks/libgcc_s.1.dylib` with macdeployqtfix.

**Comment by bgallois** [comment]
Current working workaround is to call macdeployqt (Qt 6.3.0), copy libgcc_s.1.1.dylib manually and then call macdeployqtfix.
https://github.com/FastTrackOrg/FastTrack/blob/eedf8df0c96dff2ea4548dfca36616538050d594/.github/workflows/build.yml#L120-L123

**Comment by skyfall174** [comment]
Is it work also for m1 chips?
