### ISSUE TITLE
Unreadable font of the GUI on Windows

### ISSUE THREAD

**Issue by romainbrette** [bgallois/FastTrack#53]
On Windows, the user interface uses a weird font that is unreadable, as shown on the image below.
This occurs with the last version but we have also tried older ones (like 5.3.5).
Maybe a missing font that needs to be installed?

<img width="734" alt="image" src="https://user-images.githubusercontent.com/2903502/201089610-7bd7225d-e75b-4e97-8444-b00e80bdb8a8.png">

**Comment by bgallois** [comment]
It seems to be a problem with localization, you can try enabling the Unicode UTF-8 for worldwide language support.

On Windows, go to (Control Panel)->(Region)->(Administrative)->(Change system locale)->(Use Unicode UTF-8 for worldwide language support)
