### ISSUE TITLE
[mac] Cannot open application

### ISSUE THREAD

**Issue by gamselem** [bgallois/FastTrack#57]
Hello,

I downloaded the latest version of FastTrack on my Mac and cannot open the application. I get the following error report:

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libspqr_cuda.3.dylib
  Referenced from: /Applications/FastTrack.app/Contents/Frameworks/libspqr.3.dylib
  Reason: image not found

I am on Mac OS X 10.15.7 (19H1922).
Thanks,
Gabriel

**Comment by bgallois** [comment]
Mac OSX Catalina (10.15) life ended November 30, 2022, so I do not expect the App to work anymore on this version. I bumped the minimum required macOS version with ed287feb1514a0019aeb6e5bb86bc3ce5c9f8d6e to avoid any confusion.

If this error persists with Mac OSX >= 11.7 feel free to reopen this issue.

**Comment by gamselem** [comment]
I updated my computer but still get the following error when trying to open FastTrack:

> OS Version:            macOS 12.6.7 (21G651)
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    Namespace DYLD, Code 1 Library missing
> Library not loaded: '@rpath/libspqr_cuda.3.dylib'
> Referenced from: '/Applications/FastTrack.app/Contents/Frameworks/libspqr.3.dylib'
> Reason: tried: '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file)
> (terminated at launch; ignore backtrace)
> 
>

**Comment by bgallois** [comment]
Hope the latest version built using an up-to-date system will fix this issue https://fasttrack.sh/download/Continuous/FastTrack.dmg because I do not have a lot of leeway on the macOS App production.

**Comment by gamselem** [comment]
still not...

> 
> Termination Reason:    Namespace DYLD, Code 1 Library missing
> 
> (terminated at launch; ignore backtrace)
> 

But the version from about 1 year ago (which I deleted when I installed the new version) was working! Is there any way we can have access to the corresponding .dmg?

**Comment by bgallois** [comment]
You can access and install previous versions at https://github.com/FastTrackOrg/FastTrack/releases until the error is fixed.

**Comment by gamselem** [comment]
Thanks! 6.3.0 doesn't open but 6.2.7 works.

**Comment by bgallois** [comment]
This error is related to vtk (required by OpenCV) that is not bundle in the App by macdeployqt.

**Comment by bgallois** [comment]
It is currently difficult for me to fix the macOS bundle creation. Macdeployqt seems to miss a lot of dependencies, https://fasttrack.sh/download/Continuous/FastTrack.dmg should work. To have a more reliable distribution, I created a Homebrew formula to install FastTrack easily on macOs:
1. Install https://brew.sh/
2. Install FastTrack:
    * `brew tap fasttrackorg/fasttrack`
    * `brew install fasttrack`
    * FastTrack-cli can be located at `/usr/local/bin/FastTrack-Cli` and directly used and FastTrack using `open /usr/local/Cellar/fasttrack/6.3.1_1/bin/FastTrack.app`.

The integration with the system is not perfect yet, but the software is still usable.

**Comment by gamselem** [comment]
thanks a lot, that works!
